CREATE TABLE Author (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  firstName VARCHAR(32) NOT NULL DEFAULT '',
  middleName VARCHAR(32) NOT NULL DEFAULT '',
  lastName VARCHAR(32) NOT NULL DEFAULT ''
) ENGINE=INNODB;

CREATE TABLE Work (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(128) NOT NULL DEFAULT '',
  lang VARCHAR(2) DEFAULT '',
  description TEXT
) ENGINE=INNODB;

CREATE TABLE WorkAuthor (
  authorId BIGINT,
  workId BIGINT,
  PRIMARY KEY (authorId, workId),
  CONSTRAINT FK_WorkAuthor_Author FOREIGN KEY (authorId) REFERENCES Author(id) ON DELETE CASCADE,
  CONSTRAINT FK_WorkAuthor_Work FOREIGN KEY (workId) REFERENCES Work(id) ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE Subject (
  id INT PRIMARY KEY AUTO_INCREMENT,
  subject VARCHAR(32) UNIQUE NOT NULL
) ENGINE=INNODB;

CREATE TABLE WorkSubject (
  workId BIGINT,
  subjectId INT,
  PRIMARY KEY (workId, subjectId),
  CONSTRAINT FK_WorkSubject_Work FOREIGN KEY (workId) REFERENCES Work(id) ON DELETE CASCADE,
  CONSTRAINT FK_WorkSubject_Subject FOREIGN KEY (subjectId) REFERENCES Subject(id) ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE Publisher(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64)
) ENGINE=INNODB;

CREATE TABLE Book(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  workId BIGINT,
  publisherId BIGINT,
  title VARCHAR(128) DEFAULT NULL,
  edition INT,
  lang VARCHAR(2) DEFAULT '',
  CONSTRAINT FK_Book_Work FOREIGN KEY (workId) REFERENCES Work(id)
  ON DELETE SET NULL,
  CONSTRAINT FK_Book_Publisher FOREIGN KEY (publisherId) REFERENCES  Publisher(id)
  ON DELETE SET NULL
) ENGINE=INNODB;


CREATE TABLE BookInstance (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  bookId BIGINT,
  isbn13 VARCHAR(32),
  format VARCHAR(8),
  file LONGBLOB,
  cover MEDIUMBLOB,
  CONSTRAINT FK_BookInstance_Book FOREIGN KEY (bookId) REFERENCES Book(id)
  ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE Reader (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255),
  password VARCHAR(60),
  timeRegistered TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE Download (
  readerId BIGINT,
  bookInstanceId BIGINT,
  dateDownloaded TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  readerRating INT,
  PRIMARY KEY (readerId, bookInstanceId),
  CONSTRAINT FK_Download_Reader FOREIGN KEY (readerId) REFERENCES Reader(id) ON DELETE CASCADE,
  CONSTRAINT FK_Download_BookInstance FOREIGN KEY (bookInstanceId)
    REFERENCES BookInstance(id) ON DELETE CASCADE
);