CREATE TABLE Author (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  firstName VARCHAR(32) NOT NULL DEFAULT '',
  middleName VARCHAR(32) NOT NULL DEFAULT '',
  lastName VARCHAR(32) NOT NULL DEFAULT ''
) ENGINE=INNODB;

CREATE TABLE Work (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(128) NOT NULL DEFAULT '',
  description TEXT
) ENGINE=INNODB;

CREATE TABLE WorkAuthor (
  authorId BIGINT,
  workId BIGINT,
  PRIMARY KEY (authorId, workId),
  CONSTRAINT author_fk FOREIGN KEY (authorId) REFERENCES Author(id) ON DELETE CASCADE,
  CONSTRAINT work_fk FOREIGN KEY (workId) REFERENCES Work(id) ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE Subject (
  id INT PRIMARY KEY AUTO_INCREMENT,
  subject VARCHAR(32) UNIQUE NOT NULL
) ENGINE=INNODB;

CREATE TABLE WorkSubject (
  workId BIGINT,
  subjectId INT,
  PRIMARY KEY (workId, subjectId),
  CONSTRAINT work_s_fk FOREIGN KEY (workId) REFERENCES Work(id) ON DELETE CASCADE,
  CONSTRAINT subject_w_fk FOREIGN KEY (subjectId) REFERENCES Subject(id) ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE Publisher(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64)
) ENGINE=INNODB;

CREATE TABLE Book(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  workId BIGINT,
  publisherId BIGINT,
  edition INT,
  CONSTRAINT work_b_fk FOREIGN KEY (workId) REFERENCES Work(id)
  ON DELETE SET NULL,
  CONSTRAINT publisher_b_fk FOREIGN KEY (publisherId) REFERENCES  Publisher(id)
  ON DELETE SET NULL
) ENGINE=INNODB;


CREATE TABLE BookInstance (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  bookId BIGINT,
  isbn13 VARCHAR(32),
  format VARCHAR(8),
  file LONGBLOB,
  CONSTRAINT FK_BookInstance_Book FOREIGN KEY (bookId) REFERENCES Book(id)
  ON DELETE CASCADE
) ENGINE=INNODB;